# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: check license header

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            added:
              - added: '**'
      - name: check header license on new files
        if: ${{ steps.filter.outputs.added == 'true' }}
        run: node .scripts/ci/check-license-header.js ${{ steps.filter.outputs.added_files }}
