# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Sync

on:
  workflow_dispatch:
  push:
    branches:
      - v1
      - v2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-to-mirrors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - uses: pnpm/action-setup@v4
        with:
          version: 10.x.x
          run_install: true

      - name: Build packages
        run: pnpm build

      - name: Sync
        run: .github/sync-to-mirrors.sh
        env:
          BUILD_BASE: ${{ github.workspace }}/plugins
          API_TOKEN_GITHUB: ${{ secrets.ORG_TAURI_BOT_PAT }}
